### ISSUE TITLE
Cannot deploy the Heroku

### ISSUE THREAD

**Issue by HristoEftimov** [nicolewhite/slack-meme#32]
I have tried to deploy the project to Heroku, but the following error appears:
```
-----> Python app detected
-----> Installing python-3.6.2
-----> Installing pip
-----> Noticed cffi. Bootstrapping libffi.
-----> Installing requirements with pip
       Collecting cryptography==1.7.1 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 1))
         Downloading cryptography-1.7.1.tar.gz (420kB)
       Collecting Flask==0.10.1 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 2))
         Downloading Flask-0.10.1.tar.gz (544kB)
       Collecting idna==2.2 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 3))
         Downloading idna-2.2-py2.py3-none-any.whl (55kB)
       Collecting itsdangerous==0.24 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 4))
         Downloading itsdangerous-0.24.tar.gz (46kB)
       Collecting Jinja2==2.7.3 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 5))
         Downloading Jinja2-2.7.3.tar.gz (378kB)
       Collecting MarkupSafe==0.23 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 6))
         Downloading MarkupSafe-0.23.tar.gz
       Collecting pyOpenSSL==16.2.0 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 7))
         Downloading pyOpenSSL-16.2.0-py2.py3-none-any.whl (43kB)
       Collecting requests==2.12.4 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 8))
         Downloading requests-2.12.4-py2.py3-none-any.whl (576kB)
       Collecting Werkzeug==0.10.4 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 9))
         Downloading Werkzeug-0.10.4-py2.py3-none-any.whl (293kB)
       Collecting wsgiref==0.1.2 (from -r /tmp/build_50dda189b96b1e19942325c9de8a3aa9/nicolewhite-slack-meme-b287f3b/requirements.txt (line 10))
         Downloading wsgiref-0.1.2.zip
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-skwl3ytb/wsgiref/setup.py", line 5, in <module>
               import ez_setup
             File "/tmp/pip-build-skwl3ytb/wsgiref/ez_setup/__init__.py", line 170
               print "Setuptools version",version,"or greater has been installed."
                                        ^
           SyntaxError: Missing parentheses in call to 'print'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-skwl3ytb/wsgiref/
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by pc-mreeves** [comment]
I fixed this by creating a file named "runtime.txt" with this:
`python-2.7.14`

Then you add the file and commit it to heroku via: `git push heroku master`... 

The issue is I guess heroku tries to use python 3 and this code is mildly incompatible with 3.

**Comment by robinwo** [comment]
Same issue here.

**Comment by aoberoi** [comment]
might be solved by #40? can someone give it a try?

**Comment by aoberoi** [comment]
given the lack of feedback, and the changes since #50, i'm closing this issue. if anyone is still experiencing this, feel free to comment and we'll reopen.

**Comment by rohitnairtech** [comment]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gani2gnm/functools32/

 !     Push rejected, failed to compile Python app.

I'm getting this!
